version: "4"

services:
  numberfansbot_telegram_bot:
    container_name: numberfansbot_telegram_bot
    command: uvicorn Bot.admin_panel:app --host 0.0.0.0 --port $PORT --lifespan off
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile

